// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF2sAt8sLa-J-zrTdGOWbGdXyR7kNG3UE',
    appId: '1:120489517550:web:47e61f30637e8de5a52eff',
    messagingSenderId: '120489517550',
    projectId: 'quiz-app-92610',
    authDomain: 'quiz-app-92610.firebaseapp.com',
    storageBucket: 'quiz-app-92610.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpCOmbK9IbV3Dx2-bH1zWt1xC2rWquljw',
    appId: '1:120489517550:android:c182b840e5b31a98a52eff',
    messagingSenderId: '120489517550',
    projectId: 'quiz-app-92610',
    storageBucket: 'quiz-app-92610.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC28zdm4zZYYvfoL0Fcib6COll_lfMHb5M',
    appId: '1:120489517550:ios:dde900948f546fcba52eff',
    messagingSenderId: '120489517550',
    projectId: 'quiz-app-92610',
    storageBucket: 'quiz-app-92610.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC28zdm4zZYYvfoL0Fcib6COll_lfMHb5M',
    appId: '1:120489517550:ios:dde900948f546fcba52eff',
    messagingSenderId: '120489517550',
    projectId: 'quiz-app-92610',
    storageBucket: 'quiz-app-92610.appspot.com',
    iosBundleId: 'com.example.myApp',
  );
}
